s2i 增加 report，记录关键执行过程的信息

diff --git a/s2e/s2i b/s2e/s2i
--- a/s2e/s2i
+++ b/s2e/s2i
@@ -33,9 +33,9 @@ USAGE="
 
 "
 echo "${USAGE}"
-mkdir -p .s2i/
 if [[ $# -lt 1 ]];then
     echo "${USAGE}"
+    exit 1
 else
     SRC_TOP=$(realpath $1)
 fi
@@ -44,6 +44,9 @@ if [[ $# -gt 1 ]];then
     ACTION_STAGE=$2
 else
     ACTION_STAGE="ACTION_ALL"
+fi
+if [[ -z ${CI_PROJECT_PATH} ]];then
+  CI_PROJECT_PATH="$(git rev-parse --show-toplevel)/"
 fi
 if [[ -z ${CI_PROJECT_PATH} ]];then
 CUR_DIR=$(pwd)
@@ -65,8 +68,11 @@ fi
 if [[ "" == ${DEFAULT_NS} ]];then
     DEFAULT_NS="default"
 fi
+echo "SRC_TOP=${SRC_TOP}"
 echo "CI_PROJECT_PATH=${CI_PROJECT_PATH}"
 echo "DEFAULT_NS=${DEFAULT_NS}"
+S2I_REPORT_DIR=${CI_PROJECT_PATH}/.s2i/${CI_PROJECT_NAME:-${basename ${SRC_TOP}}}/${CI_JOB_STAGE}
+mkdir -p ${S2I_REPORT_DIR}
 
 function do_src_get_srctype_by_topdir()
 {
@@ -255,7 +261,7 @@ function do_artifact_build()
             echo "not support yet"
             ;;
         *)
-            echo "not support source, or detect fail"
+            echo "not support source, or detect fail, commit your build script to ${CI_PROJECT_PATH}/build.sh"
             ;;
     esac
 }
@@ -389,9 +395,8 @@ function do_docker_build()
             set -e
             slot=$((${slot} + 1))
 
-            mkdir -p ${CI_PROJECT_PATH}/.s2i
-            echo ${DOCKER_URL} >> .s2i/img.${SRC_REPO_NAME}.${DOCKER_SUBDIR_NAME}.${DOCKER_SVC_PORTS}.html
-            echo ${DOCKER_URL} >> .s2i/s2i.${SRC_REPO_NAME}.${DOCKER_SUBDIR_NAME}.${DOCKER_SVC_PORTS}.img.txt
+            #report
+            echo ${DOCKER_URL} >> ${S2I_REPORT_DIR}/s2i.${SRC_REPO_NAME}.${DOCKER_SUBDIR_NAME}.${DOCKER_SVC_PORTS}.img.txt
         done
         
         set +e
@@ -499,6 +504,13 @@ function do_deploy_k8s()
                     kubectl set image -n ${MY_K8S_NS} deployments ${SVCNAME} ${SVCNAME}=${DOCKER_URL}
                 else
                     bash ${SCRIPT_DIR}/k8s-app-import ${DOCKER_URL} ${SVCNAME} ${MY_K8S_NS} "${DOCKER_SVC_PORTS}" ${K8S_AUTOCD} ${K8S_DOMAIN_INTERNAL} ${K8S_DOMAIN_PUBLIC}
+                    #report
+                    set +e
+                    kubectl get -n ${MY_K8S_NS}  service ${SVCNAME}  -o yaml > ${S2I_REPORT_DIR}/${SVCNAME}.service.yaml
+                    kubectl get -n ${MY_K8S_NS}  ingress ${SVCNAME}  -o yaml > ${S2I_REPORT_DIR}/${SVCNAME}.ingress.yaml
+                    kubectl get -n ${MY_K8S_NS}  ingress ${SVCNAME}-public  -o yaml > ${S2I_REPORT_DIR}/${SVCNAME}.ingress.public.yaml
+                    kubectl get -n ${MY_K8S_NS}  ingress ${SVCNAME}-internal  -o yaml > ${S2I_REPORT_DIR}/${SVCNAME}.ingress.internal.yaml
+                    set -e
                 fi
             done
             slot=$(( $slot + 1 ))
