减少s2i冗余代码，s2i 的多module 支撑去除；应该多次调用 s2i 来等价达到效果

diff --git a/s2e/s2i b/s2e/s2i
--- a/s2e/s2i
+++ b/s2e/s2i
@@ -4,6 +4,7 @@
 #email: jimin.huang@benload.com
 #email: jimminh@163.com
 set -e
+set +x
 
 ###################################################################
 THIS_SCRIPT=$(realpath $(cd "$(dirname "${BASH_SOURCE:-$0}")"; pwd)/$(basename ${BASH_SOURCE:-$0}))
@@ -101,30 +102,21 @@ function do_src_get_srctype_by_topdir()
     eval ${DETECT_NODEJS}
     if [[ -n $(eval ${DETECT_JAVA}) ]];then
         pom=`echo $(eval ${DETECT_JAVA}) | head -n 1`
-#        SRC_TOP=`echo $(realpath $(dirname ${pom})) | sort | head -n 1`
         SRC_TYPE=java
         echo "SRC_TYPE=${SRC_TYPE}"
-        #mvn --file ${SRC_TOP} -N  -Dexec.executable='echo'  -Dexec.args='${project.version}'  org.codehaus.mojo:exec-maven-plugin:1.3.1:exec 
-        #SRC_VERSION=`mvn --file ${SRC_TOP} -q -N -Dexec.executable='echo'  -Dexec.args='${project.version}'  org.codehaus.mojo:exec-maven-plugin:1.3.1:exec | tail -n 1`
     elif [[ -n $(eval ${DETECT_NODEJS}) ]];then
-#        package=`echo $(eval ${DETECT_NODEJS}) | head -n 1`
-#        SRC_TOP=$(realpath $(dirname ${package}))
         SRC_TYPE=nodejs
         echo "SRC_TYPE=${SRC_TYPE}"
-        #SRC_VERSION=$(cd ${SRC_TOP};npm run packageVersion |tail -n 1)
     elif [[ -n $(eval ${DETECT_DEFAULT_GIT}) ]];then
-#        topfile=`echo $(eval ${DETECT_DEFAULT_GIT}) | head -n 1 | awk '{print $1}'`
-#        SRC_TOP=`echo $(realpath $(dirname ${topfile})) | head -n 1`
         SRC_TYPE=none
         echo "SRC_TYPE=${SRC_TYPE}"
-        #SRC_VERSION="$(date +%Y%m%d)-$(git rev-parse --short HEAD)"
     else
         SRC_TYPE=none
         echo "SRC_TYPE=${SRC_TYPE}"
         SRC_VERSION="v1"
         echo "Warn can't detect SRC_VERSION !!!!"
     fi
-    echo "SRC_TYPE=${SRC_TYPE}"
+    echo "检测为 SRC_TYPE=${SRC_TYPE}"
     echo CI_PROJECT_REPOSITORY_LANGUAGES=${CI_PROJECT_REPOSITORY_LANGUAGES}
     if [[ -n $(eval ${DETECT_DEFAULT_GIT}) ]];then
         PWD_HAVE_DOT_GIT=1
@@ -143,12 +135,12 @@ function do_src_get_reponame()
     fi
     if [[ -n ${TEAMCITY_GIT_PATH} ]];then
         echo "Teamcity CICD"
-        SRC_BRANCHER_NAME=$(git branch | grep \* | cut -d ' ' -f2)
+        SRC_BRANCHER_NAME=${BRANCH_NAME:-$(git branch |egrep '\*' |  perl -n -e 'm/[*]\s+\W*(\w+)/g;print $1')}
         SRC_REPO_NAME=${TEAMCITY_BUILDCONF_NAME}
         BUILD_COUNTER="t${BUILD_NUMBER}"
     elif [[ -n ${JENKINS_URL} ]];then
         echo "Jenkins CICD"
-        SRC_BRANCHER_NAME=${BRANCH_NAME}
+        SRC_BRANCHER_NAME=${BRANCH_NAME:-$(git branch |egrep '\*' |  perl -n -e 'm/[*]\s+\W*(\w+)/g;print $1')}
         SRC_REPO_NAME=$(git config remote.origin.url | perl -n -e 'm/.+\/([-_\w]+).git/g;print $1')
         BUILD_COUNTER="j${BUILD_NUMBER}"
     elif [[ -n ${GITLAB_CI} ]];then
@@ -158,19 +150,18 @@ function do_src_get_reponame()
         BUILD_COUNTER="g${CI_PIPELINE_ID}"
     elif [[ -n ${GITHUB_ACTIONS} ]];then
         echo "GITHUB CICD"
-        SRC_BRANCHER_NAME=$(git branch | grep \* | cut -d ' ' -f2)
+        SRC_BRANCHER_NAME=$(git branch |egrep '\*' |  perl -n -e 'm/[*]\s+\W*(\w+)/g;print $1')
         SRC_REPO_NAME=$(basename $(realpath ${CI_PROJECT_PATH}))
         BUILD_COUNTER="$(date +%Y%m%d)"
     else
         echo "manual CICD"
-        SRC_BRANCHER_NAME=$(git branch | grep \* | cut -d ' ' -f2)   
+        SRC_BRANCHER_NAME=$(git branch |egrep '\*' |  perl -n -e 'm/[*]\s+\W*(\w+)/g;print $1')
         SRC_REPO_NAME=$(basename $(realpath ${CI_PROJECT_PATH}))
         BUILD_COUNTER="c1"
     fi
     if [[ -f ${SRC_TOP}/VERSION ]]; then
         SRC_VERSION=$(head -n 1 ${SRC_TOP}/VERSION | perl -ne '$_ =~ /((0|[1-9][0-9]*).(0|[1-9][0-9]*).?(0|[1-9][0-9]*)*)/;print $1')
     else
-        echo "warn, you can place version into VERSION file. eg. echo 1.0.0 > ${SRC_TOP}/VERSION"
         SRC_VERSION=1.0.0
     fi
     if [[ -n ${CI_COMMIT_SHORT_SHA} ]];then
@@ -178,6 +169,7 @@ function do_src_get_reponame()
     else
       SRC_GIT_COMMIT_ID="$(cd ${SRC_TOP};git rev-parse --short HEAD )"
     fi
+    
     echo "# SRC_TOP=${SRC_TOP}"
     echo "# SRC_BRANCHER_NAME=${SRC_BRANCHER_NAME}"
     echo "# SRC_VERSION=${SRC_VERSION}"
@@ -253,6 +245,7 @@ function do_artifact_build_java()
 function do_artifact_build()
 {
     echo "$FUNCNAME"
+    echo "自动检测源码类型，并做artifact 构建"
     if [[ ${ARTIFACT_DEPLOY} -gt 0 ]];then
         ARTIFACT_DEPLOY=1
     else
@@ -365,6 +358,10 @@ function do_docker_build_by_dockerfile()
       echo "Error, do_docker_build_by_dockerfile /path/to/dockerfile "
       exit 1
   fi
+  if [[ ${DOCKER_BUILD:-0} -eq 0 ]];then
+      echo "DOCKER_BUILD=${DOCKER_BUILD}, exit 0"
+      exit 0
+  fi
   local DOCKERFILE="${1}"
   do_docker_get_imgurl_by_dockerfile ${DOCKERFILE}
 
@@ -410,56 +407,17 @@ function do_docker_build_by_dockerfile()
   set -e
   echo -e "\n\n"
 }
-
-function do_docker_build()
+function do_deploy_k8s_by_dockerfile()
 {
     echo "$FUNCNAME"
-    if [[ -z ${DOCKER_BUILD} ]];then
-        DOCKER_BUILD=1
-    fi
-    if [[ ${DOCKER_BUILD} -eq 0 ]];then
-        echo "DOCKER_BUILD=${DOCKER_BUILD}, exit 0"
-        exit 0
-    fi
-    
-    echo "detect Dockerfile"
-    #DETECT_DOCKERFILE="find ${SRC_TOP}   -maxdepth 1 -iname Dockerfile | sort"
-    if [[ ${S2I_MUTI_DOCKERFILE} -gt 0 ]];then
-      DETECT_DOCKERFILE="find ${SRC_TOP} -maxdepth 1 -type f  -regextype posix-egrep -iregex '.*Dockerfile.*'"
-    else
-      DETECT_DOCKERFILE="find ${SRC_TOP} -maxdepth 1 -type f  -regextype posix-egrep -iregex '.*Dockerfile'"
-    fi
-    eval ${DETECT_DOCKERFILE}
-    eval ${DETECT_DOCKERFILE} | while read d;do
-        if [[ -n $(eval ${DETECT_DOCKERFILE}) ]];then
-            DOCKFILE=$(realpath `echo ${d} | head -n 1`)
-            DOCKFILE_DIR=$(dirname ${DOCKFILE})
-        else
-            echo "can't detect Dockerfile"
-            exit 0
-        fi
+  if [[ $# -eq 0 ]];then
+      echo "Error, usage: $FUNCNAME /path/to/dockerfile "
+      exit 1
+  fi
+    local dockerfile=${1}
 
-        echo "########################################## ${ACTION_STAGE}"
-        do_docker_build_by_dockerfile ${d}
-    done
-}
+    do_docker_get_imgurl_by_dockerfile ${dockerfile}
 
-function do_deploy_k8s()
-{
-    echo "$FUNCNAME"
-    TRYTOP=$(xdir=${SCRIPT_DIR};cd ${SCRIPT_DIR}; while /usr/bin/test ! -e .TOP ; do \
-            xdir=`cd ../;pwd`;                       \
-            if [ "$xdir" = "/" ] ; then              \
-               echo  1>&2; \
-               break;                               \
-            fi ;                                    \
-            cd $xdir;                               \
-            done ;                                  \
-            pwd;)
-    WORKDIR=$(pwd)
-    if [[ -z ${TRYTOP} ]];then
-        TRYTOP=${WORKDIR}
-    fi
     if [[ -z ${K8S_AUTOCD} ]];then
         K8S_AUTOCD=1
     fi
@@ -475,9 +433,7 @@ function do_deploy_k8s()
     if [[ -z ${K8S_DOMAIN_PUBLIC} ]];then
         K8S_DOMAIN_PUBLIC="bu5-idc.benload.com"
     fi
-    
 
-    
     if [[ -z ${K8S_SVCNAMES} ]];then
         K8S_SVCNAMES=${SRC_REPO_NAME}
     fi
@@ -505,14 +461,7 @@ function do_deploy_k8s()
     echo "K8S_DOMAIN_INTERNAL=${K8S_DOMAIN_INTERNAL}"
     echo "K8S_DOMAIN_PUBLIC=${K8S_DOMAIN_PUBLIC}"
     echo "##########################################"
-    echo "detect Dockerfile"
-    DETECT_DOCKERFILE="find ${SRC_TOP}   -maxdepth 1 -iname Dockerfile | sort"
-    eval ${DETECT_DOCKERFILE}
-    DOCKERFILE_COUNT=`eval ${DETECT_DOCKERFILE}|wc -l`
-    if [[ ${DOCKERFILE_COUNT} -eq 0 ]];then
-        echo "no Dockerfile detect"
-        exit 0
-    fi
+
     kubectl get node
     kubectl cluster-info
     ### ensure ns exists
@@ -523,37 +472,57 @@ function do_deploy_k8s()
     if [[ ${rv} -ne 0 ]];then
         kubectl create  namespace ${K8S_NS}
     fi
-    i=0
+     
+
+    if [ ${K8S_AUTOCD} -gt 0 ];then
+        for SVCNAME in ${K8S_SVCNAMES};do
+            set -x
+            bash ${SCRIPT_DIR}/k8s-app-import ${DOCKER_URL} ${SVCNAME} ${K8S_NS} "${DOCKER_SVC_PORTS}" ${K8S_AUTOCD} ${K8S_DOMAIN_INTERNAL} ${K8S_DOMAIN_PUBLIC}
+            set +x
+            #report
+            set +e
+            kubectl get ingress -n ${K8S_NS} |egrep ${SVCNAME} 2>/dev/null
+            rv=$?
+            set -e
+        done
+    else
+        echo "K8S_AUTOCD=${K8S_AUTOCD}, do nothing"
+    fi
+}
+function do_docker_action()
+{
+    echo "$FUNCNAME"
+    
+    echo "Detect Dockerfile"
+    #DETECT_DOCKERFILE="find ${SRC_TOP}   -maxdepth 1 -iname Dockerfile | sort"
+    if [[ ${S2I_MUTI_DOCKERFILE} -gt 0 ]];then
+      DETECT_DOCKERFILE="find ${SRC_TOP} -maxdepth 1 -type f  -regextype posix-egrep -iregex '.*Dockerfile.*'"
+    else
+      DETECT_DOCKERFILE="find ${SRC_TOP} -maxdepth 1 -type f  -regextype posix-egrep -iregex '.*Dockerfile'"
+    fi
+    eval ${DETECT_DOCKERFILE}
     eval ${DETECT_DOCKERFILE} | while read d;do
-        i=$(( $i + 1 ))
         if [[ -n $(eval ${DETECT_DOCKERFILE}) ]];then
-            #DOCKFILE=$(realpath `echo $(eval ${DETECT_DOCKERFILE})| head -n 1`)
-            DOCKFILE=$(realpath `echo ${d} | head -n 1`)
-            DOCKFILE_DIR=$(dirname ${DOCKFILE})
+            DOCKERFILE=$(realpath "${d}")
         else
             echo "can't detect Dockerfile"
             exit 0
         fi
-        if [[ ${DOCKERFILE_COUNT} -gt 0 ]];then
-            K8S_SVCNAMES=$(basename $(dirname ${DOCKFILE}))
-        fi
-        
-        if [ ${K8S_AUTOCD} -gt 0 ];then
-          for MY_K8S_NS in ${K8S_NS};do
-            echo "$i##########################################${DOCKFILE}"
-            do_docker_get_imgurl_by_dockerfile ${d}
-            for SVCNAME in ${K8S_SVCNAMES};do
-                bash ${SCRIPT_DIR}/k8s-app-import ${DOCKER_URL} ${SVCNAME} ${MY_K8S_NS} "${DOCKER_SVC_PORTS}" ${K8S_AUTOCD} ${K8S_DOMAIN_INTERNAL} ${K8S_DOMAIN_PUBLIC}
-                #report
-                set +e
-                kubectl get ingress -n ${MY_K8S_NS} |egrep ${SVCNAME} 2>/dev/null
-                rv=$?
-                set -e
-            done
-          done
-        fi
+        echo "########################################## ${ACTION_STAGE}"
+        case ${ACTION_STAGE} in
+            docker)
+                do_docker_build_by_dockerfile ${DOCKERFILE}
+                ;;
+            deploy)
+                do_deploy_k8s_by_dockerfile ${DOCKERFILE}
+                ;;
+            *)
+                ;;
+        esac
     done
 }
+
+
 
 function s2i_metric()
 {
@@ -578,32 +547,6 @@ export SRC_TOP
 ###################################################################
 
 
-# check config valid, not valid will regenerate
-set +e
-gitlab current-user get > /dev/null 2>&1
-RV=$?
-set -e
-
-if [[ ${RV} -ne 0 ]];then
-  if [[ -d ${RUNNER_HOME} ]];then
-# gitlab cli config file not exist
-cat > ${RUNNER_HOME}/.python-gitlab.cfg <<EOF
-[global]
-default = default
-ssl_verify = true
-timeout = 5
-
-[default]
-url = ${CI_SERVER_URL}
-private_token = ${CI_PRIVATE_TOKEN}
-api_version = 4
-EOF
-perl -ni -e "s#url.+#url = ${CI_SERVER_URL}#g;print" ${RUNNER_HOME}/.python-gitlab.cfg
-perl -ni -e "s#private_token.+#private_token = ${CI_PRIVATE_TOKEN}#g;print" ${RUNNER_HOME}/.python-gitlab.cfg
-  fi
-fi
-
-
 case ${ACTION_STAGE} in
     anal*)
         do_src_analysis
@@ -612,31 +555,31 @@ case ${ACTION_STAGE} in
         do_artifact_build
         ;;
     docker)
-        do_docker_build
+        do_docker_action
         ;;
     deploy)
         export DEPLOYMENT_UPDATE_IMG=1
         export DEPLOYMENT_DEFAULT=1
         export DEPLOYMENT_BLUE=0
-        do_deploy_k8s
+        do_docker_action
         ;;
     deploy-update-default)
         export DEPLOYMENT_UPDATE_IMG=1
         export DEPLOYMENT_DEFAULT=1
         export DEPLOYMENT_BLUE=0
-        do_deploy_k8s
+        do_docker_action
         ;;
     deploy-update-blue)
         export DEPLOYMENT_UPDATE_IMG=1
         export DEPLOYMENT_DEFAULT=0
         export DEPLOYMENT_BLUE=1
-        do_deploy_k8s
+        do_docker_action
         ;;
     deploy-insert-default)
         export DEPLOYMENT_UPDATE_IMG=0
         export DEPLOYMENT_DEFAULT=1
         export DEPLOYMENT_BLUE=0
-        do_deploy_k8s
+        do_docker_action
         ;;
     ACTION_ALL*)
         echo "自动检测源码类型，并做artifact 构建，docker 构建"
@@ -645,7 +588,7 @@ case ${ACTION_STAGE} in
         export DEPLOYMENT_UPDATE_IMG=1
         export DEPLOYMENT_DEFAULT=1
         export DEPLOYMENT_BLUE=0
-        do_deploy_k8s
+        do_docker_action
         ;;
     help*)
         echo "${USAGE}"
@@ -668,3 +611,4 @@ case ${ACTION_STAGE} in
         echo "unkown action"
         ;;
 esac
+
